blank_issues_enabled: true
contact_links:
  - name: PS2 Space discord server
    url: https://discord.gg/JryKTfs275
    about: Almost everyone that works on this project is there! check the "#sd2psx-ps2xmc2" channel
    
